import os
import re
import shutil
from pathlib import Path

STANDARD_RATES = [44100, 48000, 88200, 96000, 176400, 192000, 352800, 384000]
STANDARD_QUANTUMS = [32, 64, 128, 256, 512, 1024, 2048, 4096, 8192]


class PipeWireConfigManager:
    """PipeWire の設定ファイル (~/.config/pipewire/) の読み書き・パース・バックアップを管理するクラス"""

    def __init__(self):
        self.config_dir = Path.home() / ".config" / "pipewire"
        self.pw_conf_d = self.config_dir / "pipewire.conf.d"
        self.client_conf_d = self.config_dir / "client.conf.d"

        # デフォルトで保存・編集するドロップイン設定ファイル
        self.clock_conf_file = self.pw_conf_d / "10-clock.conf"
        self.resample_conf_file = self.client_conf_d / "10-resample.conf"

        self._ensure_directories()

    def _ensure_directories(self):
        """必要なディレクトリ構造を作成"""
        self.config_dir.mkdir(parents=True, exist_ok=True)
        self.pw_conf_d.mkdir(parents=True, exist_ok=True)
        self.client_conf_d.mkdir(parents=True, exist_ok=True)

    def load_clock_settings(self):
        """
        クロック/サンプリングレート設定を読込。
        10-clock.conf または pipewire.conf.d/*.conf からパースし、
        見つからない場合は標準デフォルト値を返します。
        """
        settings = {
            "default.clock.rate": 48000,
            "default.clock.allowed-rates": [44100, 48000, 88200, 96000],
            "default.clock.min-quantum": 32,
            "default.clock.max-quantum": 2048,
            "default.clock.quantum": 1024,
        }

        # pipewire.conf.d 内の conf ファイルを検索して読み込む
        for conf_file in sorted(self.pw_conf_d.glob("*.conf")):
            try:
                content = conf_file.read_text(encoding="utf-8")
                parsed = self._parse_spa_context_properties(content)
                settings.update(parsed)
            except Exception as e:
                print(f"Failed to load {conf_file}: {e}")

        return settings

    def load_resample_settings(self):
        """
        client.conf.d からリサンプル設定を読込。
        """
        settings = {
            "resample.quality": 4,
            "resample.disable": False,
            "channelmix.normalize": True,
            "channelmix.upmix": True,
            "channelmix.upmix-method": "psd",
        }

        for conf_file in sorted(self.client_conf_d.glob("*.conf")):
            try:
                content = conf_file.read_text(encoding="utf-8")
                parsed = self._parse_spa_stream_properties(content)
                settings.update(parsed)
            except Exception as e:
                print(f"Failed to load {conf_file}: {e}")

        return settings

    def save_clock_settings(self, rate, allowed_rates, min_quantum=None, max_quantum=None, quantum=None):
        """
        ~/.config/pipewire/pipewire.conf.d/10-clock.conf にクロック設定を書き出し。
        """
        self._ensure_directories()

        # バックアップ作成
        if self.clock_conf_file.exists():
            shutil.copy2(self.clock_conf_file, str(self.clock_conf_file) + ".bak")

        rates_str = ", ".join(str(r) for r in sorted(set(allowed_rates)))

        lines = [
            "# Generated by GUIPipeWire - Clock Configuration",
            "context.properties = {",
            f"    default.clock.rate = {int(rate)}",
            f"    default.clock.allowed-rates = [ {rates_str} ]",
        ]

        if min_quantum is not None:
            lines.append(f"    default.clock.min-quantum = {int(min_quantum)}")
        if max_quantum is not None:
            lines.append(f"    default.clock.max-quantum = {int(max_quantum)}")
        if quantum is not None:
            lines.append(f"    default.clock.quantum = {int(quantum)}")

        lines.append("}")
        lines.append("")

        self.clock_conf_file.write_text("\n".join(lines), encoding="utf-8")
        return str(self.clock_conf_file)

    def save_resample_settings(self, quality, disable=False, normalize=True, upmix=True, upmix_method="psd"):
        """
        ~/.config/pipewire/client.conf.d/10-resample.conf にクライアント設定を書き出し。
        """
        self._ensure_directories()

        # バックアップ作成
        if self.resample_conf_file.exists():
            shutil.copy2(self.resample_conf_file, str(self.resample_conf_file) + ".bak")

        lines = [
            "# Generated by GUIPipeWire - Client Resample Configuration",
            "stream.properties = {",
            f"    resample.quality = {int(quality)}",
            f"    resample.disable = {'true' if disable else 'false'}",
            f"    channelmix.normalize = {'true' if normalize else 'false'}",
            f"    channelmix.upmix = {'true' if upmix else 'false'}",
            f'    channelmix.upmix-method = "{upmix_method}"',
            "}",
            "",
        ]

        self.resample_conf_file.write_text("\n".join(lines), encoding="utf-8")
        return str(self.resample_conf_file)

    def reset_custom_configs(self):
        """
        GUIPipeWireで生成した設定ファイル（またはバックアップ）をクリーンアップし、システムデフォルトにリセットします。
        """
        removed = []
        for file in [self.clock_conf_file, self.resample_conf_file]:
            if file.exists():
                file.unlink()
                removed.append(str(file))
        return removed

    def _parse_spa_context_properties(self, content):
        """SPA / PipeWire 形式の context.properties を正規表現等で抽出"""
        result = {}

        # default.clock.rate
        m = re.search(r"default\.clock\.rate\s*=\s*(\d+)", content)
        if m:
            result["default.clock.rate"] = int(m.group(1))

        # default.clock.allowed-rates
        m = re.search(r"default\.clock\.allowed-rates\s*=\s*\[(.*?)\]", content, re.DOTALL)
        if m:
            rates_raw = m.group(1).replace(",", " ").split()
            rates = []
            for r in rates_raw:
                try:
                    rates.append(int(r.strip()))
                except ValueError:
                    pass
            if rates:
                result["default.clock.allowed-rates"] = rates

        # quantums
        for qkey in ["min-quantum", "max-quantum", "quantum", "quantum-limit"]:
            m = re.search(fr"default\.clock\.{qkey}\s*=\s*(\d+)", content)
            if m:
                result[f"default.clock.{qkey}"] = int(m.group(1))

        return result

    def _parse_spa_stream_properties(self, content):
        """SPA / PipeWire 形式の stream.properties を抽出"""
        result = {}

        m = re.search(r"resample\.quality\s*=\s*(\d+)", content)
        if m:
            result["resample.quality"] = int(m.group(1))

        m = re.search(r"resample\.disable\s*=\s*(true|false)", content, re.IGNORECASE)
        if m:
            result["resample.disable"] = m.group(1).lower() == "true"

        m = re.search(r"channelmix\.normalize\s*=\s*(true|false)", content, re.IGNORECASE)
        if m:
            result["channelmix.normalize"] = m.group(1).lower() == "true"

        m = re.search(r"channelmix\.upmix\s*=\s*(true|false)", content, re.IGNORECASE)
        if m:
            result["channelmix.upmix"] = m.group(1).lower() == "true"

        m = re.search(r'channelmix\.upmix-method\s*=\s*"([^"]+)"', content)
        if m:
            result["channelmix.upmix-method"] = m.group(1)

        return result
