import os
import re
import math
import struct
import subprocess
from pathlib import Path
from PyQt5.QtCore import QThread, pyqtSignal

class PipeWireAGCManager:
    """
    Manager for configuring PipeWire WebRTC DSP echo-cancel / AGC / noise suppression module
    and generating user configuration files (~/.config/pipewire/pipewire.conf.d/99-input-dsp.conf).
    """

    def __init__(self):
        self.config_dir = Path(os.path.expanduser("~/.config/pipewire/pipewire.conf.d"))
        self.agc_conf_file = self.config_dir / "99-input-dsp.conf"

    def _ensure_directories(self):
        self.config_dir.mkdir(parents=True, exist_ok=True)

    def is_hardware_agc_enabled(self) -> bool:
        """Return True if WebRTC DSP virtual mic config file exists."""
        return self.agc_conf_file.exists()

    def get_current_dsp_settings(self) -> dict:
        """Parse current WebRTC DSP configuration."""
        settings = {
            "enabled": False,
            "gain_control": True,
            "noise_suppression": True,
            "high_pass": True,
            "voice_detection": True
        }
        if not self.agc_conf_file.exists():
            return settings

        settings["enabled"] = True
        try:
            content = self.agc_conf_file.read_text(encoding="utf-8")
            if "webrtc.gain_control = false" in content:
                settings["gain_control"] = False
            if "webrtc.noise_suppression = false" in content:
                settings["noise_suppression"] = False
            if "webrtc.high_pass_filter = false" in content:
                settings["high_pass"] = False
            if "webrtc.voice_detection = false" in content:
                settings["voice_detection"] = False
        except Exception:
            pass
        return settings

    def enable_hardware_agc(self, gain_control=True, noise_suppression=True, high_pass=True, voice_detection=True):
        """
        Create PipeWire WebRTC DSP echo-cancel module drop-in config
        to instantiate an OS-level virtual microphone with DSP effects.
        """
        self._ensure_directories()

        lines = [
            "# Generated by GUIPipeWire - WebRTC DSP (AGC & Noise Suppression)",
            "context.modules = [",
            "    {",
            "        name = libpipewire-module-echo-cancel",
            "        args = {",
            '            library.name = "aec/libspa-aec-webrtc"',
            '            node.description = "GUIPipeWire Virtual Microphone (AGC & Noise Suppression)"',
            "            source.props = {",
            '                node.name = "GUIPipeWire_AGC_Source"',
            '                node.description = "Microphone (with AGC & Noise Suppression)"',
            "            }",
            "            aec.args = {",
            f"                webrtc.gain_control = {'true' if gain_control else 'false'}",
            f"                webrtc.noise_suppression = {'true' if noise_suppression else 'false'}",
            f"                webrtc.high_pass_filter = {'true' if high_pass else 'false'}",
            f"                webrtc.voice_detection = {'true' if voice_detection else 'false'}",
            "                webrtc.extended_filter = true",
            "            }",
            "        }",
            "    }",
            "]",
            ""
        ]

        self.agc_conf_file.write_text("\n".join(lines), encoding="utf-8")
        return str(self.agc_conf_file)

    def disable_hardware_agc(self):
        """Delete WebRTC AGC drop-in configuration file."""
        if self.agc_conf_file.exists():
            self.agc_conf_file.unlink()
            return True
        return False


class MicrophoneMonitorThread(QThread):
    """
    Worker thread that monitors microphone input levels (RMS / Peak dBFS) in real time
    and performs dynamic gain auto-tracking (Software AGC) in Python.
    """
    level_updated = pyqtSignal(float, float, float, bool)  # rms_db, peak_db, current_vol, is_clipping
    agc_action = pyqtSignal(str)  # Log / notification message

    def __init__(self, source_name=None, parent=None):
        super().__init__(parent)
        self.source_name = source_name
        self.running = False
        
        # Software AGC parameters
        self.soft_agc_enabled = False
        self.target_db = -18.0          # Target volume (dBFS)
        self.noise_floor_db = -48.0     # Noise floor threshold (dBFS)
        self.attack_rate = 0.15         # Fast reduction rate on loud signals
        self.release_rate = 0.04        # Gentle amplification rate on quiet signals
        self.min_gain = 0.2             # Minimum gain (20%)
        self.max_gain = 1.5             # Maximum gain (150%)
        
        self.process = None

    def set_source(self, source_name):
        self.source_name = source_name

    def set_agc_params(self, enabled, target_db=-18.0, noise_floor_db=-48.0, max_gain=1.5):
        self.soft_agc_enabled = enabled
        self.target_db = target_db
        self.noise_floor_db = noise_floor_db
        self.max_gain = max_gain

    def run(self):
        self.running = True
        import pulsectl
        pulse = None
        try:
            pulse = pulsectl.Pulse('guipipewire-monitor')
        except Exception as e:
            self.agc_action.emit(f"PulseAudio/PipeWire connection error: {e}")

        # Stream raw 16bit 16kHz mono audio via pw-record (minimal CPU overhead)
        cmd = [
            "pw-record",
            "--channels=1",
            "--rate=16000",
            "--format=s16",
            "-"
        ]
        if self.source_name and self.source_name != "default":
            cmd.extend(["--target", self.source_name])

        try:
            self.process = subprocess.Popen(
                cmd,
                stdout=subprocess.PIPE,
                stderr=subprocess.DEVNULL,
                bufsize=1024 * 4
            )

            # 16000Hz * 1ch * 2bytes/sample * 0.05s = 1600 bytes (50ms chunks)
            chunk_size = 1600
            
            while self.running and self.process.poll() is None:
                raw_data = self.process.stdout.read(chunk_size)
                if not raw_data or len(raw_data) < 2:
                    continue

                count = len(raw_data) // 2
                samples = struct.unpack(f"<{count}h", raw_data[:count*2])
                
                # Peak & RMS calculation
                peak = max(abs(s) for s in samples)
                sum_sq = sum(s * s for s in samples)
                rms = math.sqrt(sum_sq / count)

                # Convert to dBFS (0 dBFS = 32767)
                peak_db = 20 * math.log10(max(1, peak) / 32767.0)
                rms_db = 20 * math.log10(max(1, rms) / 32767.0)
                
                is_clipping = peak >= 32000

                # Get current mic volume
                current_vol = 1.0
                source_obj = None
                if pulse:
                    try:
                        if self.source_name and self.source_name != "default":
                            source_obj = pulse.get_source_by_name(self.source_name)
                        else:
                            default_name = pulse.server_info().default_source_name
                            source_obj = pulse.get_source_by_name(default_name)
                        if source_obj:
                            current_vol = source_obj.volume.value_flat
                    except Exception:
                        pass

                # Software AGC (dynamic gain tracking)
                if self.soft_agc_enabled and pulse and source_obj:
                    # 1. Emergency clipping avoidance
                    if is_clipping or peak_db > -2.0:
                        new_vol = max(self.min_gain, current_vol * 0.8)
                        pulse.volume_set_all_chans(source_obj, new_vol)
                        self.agc_action.emit(f"[AGC] Clipping detected: Reduced gain to {int(new_vol*100)}%")
                    
                    # 2. Regular voice activity (above noise floor and deviating from target)
                    elif rms_db > self.noise_floor_db:
                        diff_db = self.target_db - rms_db
                        if abs(diff_db) > 2.5:
                            if diff_db > 0:
                                step = (diff_db / 20.0) * self.release_rate
                                new_vol = min(self.max_gain, current_vol + step)
                            else:
                                step = (abs(diff_db) / 20.0) * self.attack_rate
                                new_vol = max(self.min_gain, current_vol - step)
                            
                            if abs(new_vol - current_vol) > 0.01:
                                pulse.volume_set_all_chans(source_obj, new_vol)

                # Emit signal to UI
                self.level_updated.emit(rms_db, peak_db, current_vol, is_clipping)

        except Exception as e:
            self.agc_action.emit(f"Microphone monitor error: {e}")
        finally:
            if self.process:
                try:
                    self.process.terminate()
                except Exception:
                    pass
            if pulse:
                try:
                    pulse.close()
                except Exception:
                    pass

    def stop(self):
        self.running = False
        if self.process:
            try:
                self.process.terminate()
            except Exception:
                pass
        self.wait(1000)
