import os
import re
import math
import shutil
import struct
import subprocess
from pathlib import Path
from PyQt5.QtCore import QThread, pyqtSignal

class PipeWireAGCManager:
    """PipeWire の WebRTC DSP (AGC / ノイズ抑制 / エコーキャンセル) 設定を管理するクラス"""

    def __init__(self):
        self.config_dir = Path.home() / ".config" / "pipewire"
        self.pw_conf_d = self.config_dir / "pipewire.conf.d"
        self.agc_conf_file = self.pw_conf_d / "30-webrtc-agc.conf"
        self._ensure_directories()

    def _ensure_directories(self):
        self.config_dir.mkdir(parents=True, exist_ok=True)
        self.pw_conf_d.mkdir(parents=True, exist_ok=True)

    def is_hardware_agc_enabled(self):
        """PipeWire ネイティブの WebRTC AGC 設定が存在するか確認"""
        return self.agc_conf_file.exists()

    def enable_hardware_agc(self, gain_control=True, noise_suppression=True, high_pass=True, voice_detection=True):
        """
        PipeWire の libpipewire-module-echo-cancel (WebRTC AEC) を有効化し、
        自動ゲイン調整 & ノイズ抑制付きの仮想マイクを作成する設定を保存。
        """
        self._ensure_directories()

        lines = [
            "# Generated by GUIPipeWire - WebRTC DSP (AGC & Noise Suppression)",
            "context.modules = [",
            "    {",
            "        name = libpipewire-module-echo-cancel",
            "        args = {",
            '            library.name = "aec/libspa-aec-webrtc"',
            '            node.description = "GUIPipeWire 仮想マイク (AGC・ノイズ抑制)"',
            "            source.props = {",
            '                node.name = "GUIPipeWire_AGC_Source"',
            '                node.description = "マイク (AGC・ノイズ抑制適用済み)"',
            "            }",
            "            aec.args = {",
            f"                webrtc.gain_control = {'true' if gain_control else 'false'}",
            f"                webrtc.noise_suppression = {'true' if noise_suppression else 'false'}",
            f"                webrtc.high_pass_filter = {'true' if high_pass else 'false'}",
            f"                webrtc.voice_detection = {'true' if voice_detection else 'false'}",
            "                webrtc.extended_filter = true",
            "            }",
            "        }",
            "    }",
            "]",
            ""
        ]

        self.agc_conf_file.write_text("\n".join(lines), encoding="utf-8")
        return str(self.agc_conf_file)

    def disable_hardware_agc(self):
        """WebRTC AGC 設定ファイルを削除"""
        if self.agc_conf_file.exists():
            self.agc_conf_file.unlink()
            return True
        return False


class MicrophoneMonitorThread(QThread):
    """
    マイクの入力レベル (RMS / Peak dBFS) をリアルタイムに監視し、
    必要に応じて Python 側で自動音量均一化 (Software AGC) を行うワーカースレッド。
    """
    level_updated = pyqtSignal(float, float, float, bool)  # rms_db, peak_db, current_vol, is_clipping
    agc_action = pyqtSignal(str)  # ログ/通知メッセージ

    def __init__(self, source_name=None, parent=None):
        super().__init__(parent)
        self.source_name = source_name
        self.running = False
        
        # Software AGC 設定パラメータ
        self.soft_agc_enabled = False
        self.target_db = -18.0          # 目標音量 (dBFS)
        self.noise_floor_db = -48.0     # 無音・ノイズ判定閾値 (これ以下はゲインを上げない)
        self.attack_rate = 0.15         # 大音量時の減衰速度 (速め)
        self.release_rate = 0.04        # 小音量時の増幅速度 (ゆっくり)
        self.min_gain = 0.2             # 最小音量 (20%)
        self.max_gain = 1.5             # 最大音量 (150%)
        
        self.process = None

    def set_source(self, source_name):
        self.source_name = source_name

    def set_agc_params(self, enabled, target_db=-18.0, noise_floor_db=-48.0, max_gain=1.5):
        self.soft_agc_enabled = enabled
        self.target_db = target_db
        self.noise_floor_db = noise_floor_db
        self.max_gain = max_gain

    def run(self):
        self.running = True
        import pulsectl
        pulse = None
        try:
            pulse = pulsectl.Pulse('guipipewire-monitor')
        except Exception as e:
            self.agc_action.emit(f"PulseAudio/PipeWire 接続エラー: {e}")

        # pw-record で 16bit 16kHz mono の生音声をパイプ読み込み (CPU負荷極小)
        cmd = [
            "pw-record",
            "--channels=1",
            "--rate=16000",
            "--format=s16",
            "-"
        ]
        if self.source_name and self.source_name != "default":
            cmd.extend(["--target", self.source_name])

        try:
            self.process = subprocess.Popen(
                cmd,
                stdout=subprocess.PIPE,
                stderr=subprocess.DEVNULL,
                bufsize=1024 * 4
            )

            # 16000Hz * 1ch * 2bytes/sample * 0.05秒 = 1600 bytes (50ms ごとに集計)
            chunk_size = 1600
            
            while self.running and self.process.poll() is None:
                raw_data = self.process.stdout.read(chunk_size)
                if not raw_data or len(raw_data) < 2:
                    continue

                # 16bit リニアPCM をデコード (-32768 〜 32767)
                count = len(raw_data) // 2
                samples = struct.unpack(f"<{count}h", raw_data[:count*2])
                
                # Peak & RMS 計算
                peak = max(abs(s) for s in samples)
                sum_sq = sum(s * s for s in samples)
                rms = math.sqrt(sum_sq / count)

                # dBFS 変換 (0dBFS = 32767)
                peak_db = 20 * math.log10(max(1, peak) / 32767.0)
                rms_db = 20 * math.log10(max(1, rms) / 32767.0)
                
                is_clipping = peak >= 32000

                # 現在のマイク音量を取得
                current_vol = 1.0
                source_obj = None
                if pulse:
                    try:
                        if self.source_name and self.source_name != "default":
                            source_obj = pulse.get_source_by_name(self.source_name)
                        else:
                            default_name = pulse.server_info().default_source_name
                            source_obj = pulse.get_source_by_name(default_name)
                        if source_obj:
                            current_vol = source_obj.volume.value_flat
                    except Exception:
                        pass

                # Software AGC (自動ゲイン調整ロジック)
                if self.soft_agc_enabled and pulse and source_obj:
                    # 1. 音割れ/クリッピング緊急回避
                    if is_clipping or peak_db > -2.0:
                        new_vol = max(self.min_gain, current_vol * 0.8)
                        pulse.volume_set_all_chans(source_obj, new_vol)
                        self.agc_action.emit(f"[AGC] 音割れ検知: 音量を {int(new_vol*100)}% に抑制")
                    
                    # 2. 通常の発声時 (無音フロアより大きく、目標音量と乖離がある場合)
                    elif rms_db > self.noise_floor_db:
                        diff_db = self.target_db - rms_db
                        if abs(diff_db) > 2.5: # 2.5dB 以上のズレで調整開始
                            if diff_db > 0:
                                # 音が小さい → ゆっくり上げる
                                step = (diff_db / 20.0) * self.release_rate
                                new_vol = min(self.max_gain, current_vol + step)
                            else:
                                # 音が大きい → やや素早く下げる
                                step = (abs(diff_db) / 20.0) * self.attack_rate
                                new_vol = max(self.min_gain, current_vol - step)
                            
                            if abs(new_vol - current_vol) > 0.01:
                                pulse.volume_set_all_chans(source_obj, new_vol)

                # UI にシグナル送信
                self.level_updated.emit(rms_db, peak_db, current_vol, is_clipping)

        except Exception as e:
            self.agc_action.emit(f"マイク監視エラー: {e}")
        finally:
            if self.process:
                try:
                    self.process.terminate()
                except Exception:
                    pass
            if pulse:
                try:
                    pulse.close()
                except Exception:
                    pass

    def stop(self):
        self.running = False
        if self.process:
            try:
                self.process.terminate()
            except Exception:
                pass
        self.wait(1000)
